# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [1]:
from sklearn import cross_validation, datasets

import numpy as np

C:\Users\Admin.Ann-s\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [2]:
iris = datasets.load_iris()

In [3]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)
#аргументы - набор данных, набор меток классов, [соотношение разбиения]

In [4]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [5]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [6]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

Обучающая выборка:
[[ 6.3  2.5  5.   1.9]
 [ 6.5  3.   5.8  2.2]
 [ 5.   3.5  1.3  0.3]
 [ 5.8  2.8  5.1  2.4]
 [ 6.1  2.8  4.   1.3]]


Тестовая выборка:
[[ 5.6  2.9  3.6  1.3]
 [ 4.6  3.6  1.   0.2]
 [ 6.2  2.9  4.3  1.3]
 [ 5.   3.4  1.6  0.4]
 [ 5.7  3.   4.2  1.2]]


In [7]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

Метки классов на обучающей выборке:
[2 2 0 2 1 2 0 0 1 2 0 1 1 2 0 0 1 1 2 1 1 2 1 0 0 0 1 0 1 1 0 2 2 0 1 1 2
 0 0 2 1 0 0 0 0 1 0 1 0 0 2 1 1 0 0 1 2 0 1 0 2 2 2 1 2 1 0 1 2 1 0 0 1 2
 2 2 1 2 1 1 2 2 0 2 1 2 2 1 2 2 0 0 0 1 2 1 2 1 0 1 2 2 1 2 2]


Метки классов на тестовой выборке:
[1 0 1 0 1 1 2 2 2 0 0 1 2 0 0 2 1 0 0 0 2 1 2 2 0 1 0 0 2 2 1 0 1 1 2 1 0
 2 0 2 0 1 2 0 1]


### Стратегии проведения кросс-валидации

#### KFold

In [9]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 5): #аргументы - кол-во объектов, кол-во групп (фолдов)
    print train_indices, test_indices

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [8]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True): #хотим перемешать элементы
    print train_indices, test_indices

[0 3 4 7 9] [1 2 5 6 8]
[1 2 5 6 8] [0 3 4 7 9]


In [10]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True, random_state = 1): 
    #тобы результат работы был всегда одинаковым
    print train_indices, test_indices

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [11]:
#сохраняем соотнощение классов в обучающей и тестовой подвыборке; на вход передаем также метки классов
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2, shuffle = True, random_state = 0):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [12]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print train_indices, test_indices

[0 1 0 1 0 1 0 1 0 1]
[4 6 7 9] [0 1 2 3 5 8]
[0 1 2 3 5 8] [4 6 7 9]


#### ShuffleSplit

In [13]:
#строить случайные перестановки
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter = 10, test_size = 0.2):
    #аргументы - кол-во объектов, сколько итераций хотим, размер тестовой выборки
    print train_indices, test_indices

[2 0 7 6 9 3 8 4] [5 1]
[0 6 9 4 5 2 1 3] [8 7]
[2 9 4 0 1 3 7 6] [5 8]
[7 2 3 6 8 9 5 4] [1 0]
[0 9 2 7 4 8 6 1] [3 5]
[6 2 7 0 5 8 3 4] [1 9]
[6 1 8 9 5 2 3 0] [7 4]
[3 6 5 1 4 0 2 8] [9 7]
[8 4 1 5 2 6 3 7] [0 9]
[7 6 1 9 0 5 8 3] [2 4]


#### StratifiedShuffleSplit

In [14]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[9 8 3 5 1 4 2 6] [0 7]
[9 6 1 2 5 3 0 7] [4 8]
[3 6 9 8 2 7 0 4] [5 1]
[7 8 4 2 9 6 3 0] [5 1]


#### Leave-One-Out

In [15]:
#оставить каждый объект в тесте один раз, тесовая всегда состоит из одного объекта
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print train_indices, test_index

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators